#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Takuma Ohasawa<s23C1025wd@ws.chibalkoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import syas

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
